---
driver:
  name: vagrant

  provisioner:
    name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: debian/jessie64

suites:
  - name: default
    run_list:
    - recipe[cas_robots::default]
    attributes: 
      cas_robots:
        example:
          allow: true
          path: '/tmp/robots.txt'
          owner: 'root'
          group: 'root'
          user_agents:
            '*':
              - 'example/directory'
              - 'example/file.html'
          sitemaps:
            default: 'https://www.example.com/sitemap.xml'
        example2:
          allow: false
          path: '/tmp/example-robots.txt'
